{
 "title": "DB Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Users", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number User",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id) FROM \"Auth_user\" LIMIT 50 "
    }
   ]
  },
  { "title": "Games", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Number User in game",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id), in_game FROM \"Auth_user\"\nWHERE in_game IS TRUE\nGROUP BY in_game LIMIT 50 "
    },
    {
     "rawSql": "SELECT COUNT(id), in_game FROM \"Auth_user\"\nWHERE in_game IS FALSE\nGROUP BY in_game LIMIT 50 "
    }
   ]
  },
  {
   "title": "Number Game",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id)\nFrom \"Game_games\"\n"
    }
   ]
  },
  {
   "title": "Max speed",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT MAX(max_speed) FROM \"Game_usergame\" GROUP BY user_id LIMIT 50 "
    }
   ]
  }
 ]
}