# Generated by Django 4.2.11 on 2024-03-25 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTwoFA',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='to2fa', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('enable', models.BooleanField(default=False)),
                ('otp_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('otp_expiry_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
