# Generated by Django 4.2.11 on 2024-03-25 09:25

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('status', models.BooleanField(default=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=320, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('avatar', models.ImageField(blank=True, default='ForbiddenDeletion/default.png', null=True, upload_to='')),
                ('backup_avatar', models.ImageField(default='ForbiddenDeletion/default.png', upload_to='')),
                ('refresh_token', models.CharField(blank=True, max_length=255, null=True)),
                ('tournament_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
